arproject/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import SignupView

app_name = 'accounts'

urlpatterns = [
  path('login/', LoginView.as_view(), name='login'),
  path('logout/', LogoutView.as_view(), name='logout'),
  path('signup/', SignupView.as_view(), name='signup'),
]

arproject/arapp/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path('<int:pk>/ar_cam/', views.Ar_camViews, name="ar_cam"),
    path('video_feed/', views.video_feed_view(), name="video_feed"),
]

urlpatterns += staticfiles_urlpatterns()

arproject/arproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('mainapp.urls')),
    path('', include('arapp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

arproject/mainapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.Top_view.as_view(), name='top'),
    path('image/', views.ListImageView.as_view(), name='image-main'),
    path('image/create/', views.CreateImageView.as_view(), name='image-create'),
    path('image/detail/<int:pk>/', views.DetailImageView.as_view(), name='image-detail'),
]

arproject/accounts/models.py
from django.db import models

# Create your models here.

arproject/mainapp/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Image(models.Model):
    title = models.CharField(max_length=100)
    height = models.IntegerField(validators=[MinValueValidator(1)])
    width = models.IntegerField(validators=[MinValueValidator(1)])
    thumbnail = models.ImageField(null=False, blank=False)

    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

arproject/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
  class Meta:
    model = User
    fields = ('username',)

arproject/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import SignupForm

class SignupView(CreateView):
  model = User
  form_class = SignupForm
  template_name = 'accounts/signup.html'
  success_url = reverse_lazy('top')

arproject/arapp/views.py
import cv2
from django.http import StreamingHttpResponse
from django.shortcuts import render
from django.views import View
from pyzbar.pyzbar import decode, ZBarSymbol
from mainapp.models import *
from django.conf import settings
import numpy as np

prm = 1 #デフォルトのプライマリーキー

# グローバル変数prmを更新する関数
def update_prm(pk):
    global prm
    prm = pk

# 絵画の画像のパスを返す関数
def create_path():
    obj = Image.objects.get(id = prm)
    input_path = str(settings.BASE_DIR) + str(obj.thumbnail.url)
    return input_path

# 絵画の実際の高さを返す関数
def acqu_size_h():
    obj = Image.objects.get(id = prm)
    r_size = obj.height
    return r_size

def Ar_camViews(request, pk):
    update_prm(pk)
    video_feed_view()
    return render(request, 'arapp/ar_cam.html', {})


def video_feed_view():
    return lambda _: StreamingHttpResponse(generate_frame(), content_type='multipart/x-mixed-replace; boundary=frame')

#アフィン変換行列による絵画の画像とカメラ映像を合成する関数
def overlay(img, frame, shift, h, size, r_size):
    qr_size = 200   # QRコードの高さ
    k = size / h
    mag = (r_size / qr_size) / k    # 変換倍率

    shift_x, shift_y = shift
 
    frame_h, frame_w = frame.shape[:2]
    
    dx = shift_x
    dy = shift_y
    m = np.float32([[mag, 0, dx],[0, mag, dy]])
    frame = cv2.warpAffine(img, m, (frame_w, frame_h), frame, borderMode=cv2.BORDER_TRANSPARENT)
 
    return frame

def generate_frame():
    input_path = create_path()
    r_size = acqu_size_h()
    img = cv2.imread(input_path)

    font = cv2.FONT_HERSHEY_SIMPLEX

    
    capture = cv2.VideoCapture(1)

    capture.set(cv2.CAP_PROP_FPS, 30)

    while True:
        if not capture.isOpened():
            print("Capture is not opened.")
            break
        ret, frame = capture.read()
        if not ret:
            print("Failed to read frame.")
            break

        if ret:
            value = decode(frame, symbols = [ZBarSymbol.QRCODE])
            if value:
                for qrcode in value:
                    x, y, w, h = qrcode.rect

                    dec_inf = qrcode.data.decode('utf-8')
                    print('dec:', dec_inf)
                    frame = cv2.putText(frame, dec_inf, (x, y-6), font, .3, (255,0,0), 1, cv2.LINE_AA)

                    cv2.rectangle(frame, (x, y), (x + w, y + h), (0,255,0), 1)

                    size = img.shape[0]

                    overlay(img, frame, (x, y), h, size, r_size)

        ret, jpeg = cv2.imencode('.jpg', frame)
        byte_frame = jpeg.tobytes()

        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + byte_frame + b'\r\n\r\n')
    capture.release()

arproject/mainapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DetailView
from django.views import View
from .models import Image


class Top_view(TemplateView):
    template_name = 'mainapp/top.html'

class ListImageView(LoginRequiredMixin, ListView):
    template_name = 'mainapp/image_list.html'
    model = Image

class CreateImageView(LoginRequiredMixin, CreateView):
    template_name = 'mainapp/image_create.html'
    model = Image
    fields = ('title', 'height', 'width', 'thumbnail')
    success_url = reverse_lazy('image-main')

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super().form_valid(form)

class DetailImageView(LoginRequiredMixin, DetailView):
    template_name = 'mainapp/image_detail.html'
    model = Image

arproject/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}アカウント作成{% endblock %}
{% block h1 %}アカウント作成{% endblock %}
{% block content %}
<form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
  {% csrf_token %}
  <input type="text" name='username' class="form-control my-4" placeholder="ユーザ ID">
  <input type="password" name='password1' class="form-control mt-4" placeholder="パスワード">
  <input type="password" name='password2' class="form-control mt-4" placeholder="パスワード確認用">
  <small class="mb-2 d-block text-start">パスワードは8文字以上で設定してください。</small>
  {% if form.errors %}
  <span class="mb-2 small text-danger d-block text-start">利用できないユーザ IDやパスワードの可能性があります。入力内容を再度ご確認ください。</span>
  {% endif %}
  <button type="submit" class="btn btn-success m-2">アカウント作成</button>
</form>
{% endblock %}

arproject/arapp/templates/arapp/ar_cam.html
{% extends 'base.html' %}

{% block title %}合成ページ{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="mx-auto">
            <div id="image_area">
                <img src="/video_feed" width="100%" height="auto" />
            </div>
        </div>
    </div>
</div>

{% endblock content %}

arproject/mainapp/templates/mainapp/image_create.html
{% extends 'base.html' %}

{% block title %}絵画登録{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <form method="POST" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success mt-4">投稿する</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

arproject/mainapp/templates/mainapp/image_detail.html
{% extends 'base.html' %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
{% if object.user == request.user %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <div class="card">
        <h5 class="card-headder">{{ object.title }}</h5>
        <div class="card-header">
          <p class="card-text">高さ:{{ object.height }}</p>
          <h6 class="card-title">幅:{{ object.width }}</h6>
          <img src="{{ object.thumbnail.url }}" class="img-thumbnail" />
          <a href="{% url 'ar_cam' object.pk %}" class="btn btn-primary">合成する</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock content %}

arproject/mainapp/templates/mainapp/image_list.html
{% extends 'base.html' %}

{% block title %}絵画リスト{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>絵画リスト</h1>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    {% for item in object_list %}
      {% if item.user == request.user %}
        <div class="col-6 pb-3 mx-auto">
          <a href="{% url 'image-detail' item.pk %}" class="thumbnail">
            <img src="{{ item.thumbnail.url }}"/>
          </a>
        </div>
      {% endif %}
    {% endfor %}
  </div>
</div>

{% endblock content %}

arproject/mainapp/templates/mainapp/top.html
{% extends 'base.html' %}

{% block title %}Topページ{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
       <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h1>絵画合成アプリケーション</h1>
            <p>登録した絵画の画像とカメラの映像を合成し、拡張現実として表示します。</p>
            <p>初めての方は合成したい絵画の画像を登録してください。</p>
            <p>登録をすでに完了している方は画像リストより画像を選択し、合成を開始してください。</p>
            <a class="btn btn-info btn-rounded mx-3" href="{% url 'image-main' %}">画像リスト</a>
            <a class="btn btn-warning btn-rounded mx-3" href="{% url 'image-create' %}">画像登録</a>
        </div>
    </div>
</div>

{% endblock content %}

arproject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.rtl.min.css"
    integrity="sha384-+4j30LffJ4tgIMrq9CwHvn0NjEvmuDCOfk6Rpg2xg7zgOxWWtLtozDEEVvBPgHqE" crossorigin="anonymous">

  <!-- stylesheet -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <title>{% block title %}{% endblock title %}| 絵画合成アプリケーション</title>
</head>

<body>
  <nav class="navbar navbar-dark bg-secondary sticky-top">
    <div class="navbar-nav d-flex flex-row">
      <a class="nav-link mx-3" href="{% url 'top' %}">Topページ</a>
      <a class="nav-link mx-3" href="{% url 'image-main' %}">絵画リスト</a>
    </div>
    <div class="navbar-nav d-flex flex-row">
      {% if request.user.is_authenticated %}
      <a class="nav-link mx-3" href="{% url 'accounts:logout' %}">ログアウト</a>
      {% else %}
      <a class="nav-link mx-3" href="{% url 'accounts:login' %}">ログイン</a>
      <a class="nav-link mx-3" href="{% url 'accounts:signup' %}">会員登録</a>
      {% endif %}
    </div>
  </nav>
  <div class="'p-4">
    <h1>{% block h1 %}{% endblock %}</h1>
    {% block content %}{% endblock content %}
  </div>
</body>

</html>